name: Download emnist

on: [push]

jobs:
  download:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8
      matrix:
        torchvision-version: [0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.8.0, 0.8.1, 0.8.2, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.1, 0.11.2, 0.11.3, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.17.2, 0.18.0]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y libtinfo5
        python -m pip install --upgrade pip
        pip install numpy -U
        pip install torchvision==${{ matrix.torchvision-version }} -f https://download.pytorch.org/whl/torch_stable.html
        pip install setuptools
        pip install requests
    - name: Install package
      run: python -m pip install .
    - name: Download EMNIST dataset
      run: python examples/emnist/download.py
    - name: Extract EMNIST dataset
      run: python examples/emnist/main.py --epochs 0
