name: Download emnist

on: [push]

jobs:
  download:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 8
      matrix:
        torchvision-version: [0.10.1, 0.11.3, 0.12.0, 0.13.1, 0.14.1, 0.15.2, 0.16.2, 0.17.2, 0.18.1, 0.19.1, 0.20.1]
        include:
          - pytorch-version: 1.9.1
            torchvision-version: 0.10.1
          - pytorch-version: 1.10.2
            torchvision-version: 0.11.3
          - pytorch-version: 1.11.0
            torchvision-version: 0.12.0
          - pytorch-version: 1.12.1
            torchvision-version: 0.13.1
          - pytorch-version: 1.13.1
            torchvision-version: 0.14.1
          - pytorch-version: 2.0.1
            torchvision-version: 0.15.2
          - pytorch-version: 2.1.2
            torchvision-version: 0.16.2
          - pytorch-version: 2.2.2
            torchvision-version: 0.17.2
          - pytorch-version: 2.3.1
            torchvision-version: 0.18.1
          - pytorch-version: 2.4.1
            torchvision-version: 0.19.1
          - pytorch-version: 2.5.1
            torchvision-version: 0.20.1
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install 'numpy<2'
        pip install torch==${{ matrix.pytorch-version }}+cpu -f https://download.pytorch.org/whl/torch
        pip install torchvision==${{ matrix.torchvision-version }}+cpu -f https://download.pytorch.org/whl/torchvision
        pip install setuptools
        pip install requests
    - name: Install package
      run: python -m pip install .
    - name: Download EMNIST dataset
      run: python examples/emnist/download.py
    - name: Extract EMNIST dataset
      run: python examples/emnist/main.py --epochs 0
