name: Example plots

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 8
      matrix:
        python-version: [3.7, 3.8]
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy -U
        pip install torch==1.4.0 -f https://download.pytorch.org/whl/torch_stable.html
        pip install matplotlib
    - name: Install package
      run: python setup.py install
    - name: Preparation
      run: mkdir artifact
    - name: Plot warmup period
      run: |
        cd artifact
        python ../examples/plots/effective_warmup_period.py --output png
    - name: Plot warmup schedule
      run: |
        cd artifact
        python ../examples/plots/warmup_schedule.py --output png
    - uses: actions/upload-artifact@v3
      with:
        name: artifact_${{ matrix.os }}_${{ matrix.python-version }}
        path: artifact
