name: Example cifar10

on: [push]

jobs:
  train:

    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 8
      matrix:
        python-version: [3.8, '3.10', 3.12]
        os: [macos-latest, windows-latest, ubuntu-latest]
        include:
          - pytorch-version: 2.3.1
            torchvision-version: 0.18.1
          - pytorch-option: '+cpu'
          - pytorch-option: ''
            os: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install 'numpy<2' -U
        pip install torch==${{ matrix.pytorch-version }}${{ matrix.pytorch-option }} torchvision==${{ matrix.torchvision-version }}${{ matrix.pytorch-option }} -f https://download.pytorch.org/whl/torch_stable.html
        pip install setuptools
        pip install requests
        pip install tqdm
    - name: Install package
      run: python -m pip install .
    - name: Download a ResNet implementation
      run: |
        cd examples/cifar10/
        python download.py
    - name: Train a ResNet20 model on CIFAR dataset
      run: python examples/cifar10/main.py --epochs 1 --no-progress --no-gpu
